// File generated by Blink v0.18.0 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const StepReplication: () => void
export declare const start: {
	On: (Listener: (Player: Player, Value: void) => void) => (() => void)
}
export declare const dispatch: {
	Fire: (Player: Player, Value: unknown) => void
	FireAll: (Value: unknown) => void
	FireExcept: (Except: Player, Value: unknown) => void
	FireList: (List: Player[], Value: unknown) => void
}
