// File generated by Blink v0.18.0 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const StepReplication: () => void
export declare const start: {
	Fire: (Value: void) => void
}
export declare const dispatch: {
	On: (Listener: (Value: unknown) => void) => (() => void)
}
